import "./globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-5 bg-slate-400 flex justify-center items-center gap-5">
          <Link href={"/blog"}>Blog</Link>
          <Link href={"/name"}>Name</Link>
          <Link href={"/step02_fetching"}>Step 02</Link>
          <Link href={"/step02_fetching_revalidate"}>Step 02 Revalidate</Link>
          <Link href={"/step03_dynamic"}>Step 03</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
